# Import Library

# 미완성!!!

In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

# 시작

In [2]:
cwd = os.getcwd()
print('현재 폴더 경로 : ', cwd)
# 폴더 위치 변경
os.chdir("C:\\Users\hyunj\\Dropbox\\종합설계프로젝트\\중요\\데이터\\통합")
print('변경 후 폴더 경로 : ', cwd)
print('현재 폴더 파일 : ', os.listdir())
data = pd.read_csv('Integrated DS.csv', encoding='CP949')
print('feature 항목 : ', data.columns)
data

현재 폴더 경로 :  c:\Users\hyunj\Desktop\종합설계프로젝트
변경 후 폴더 경로 :  c:\Users\hyunj\Desktop\종합설계프로젝트
현재 폴더 파일 :  ['A92DA000', 'Data.csv', 'Integrated DS.csv', 'Integrated DStoLD.csv', 'Integrated LD.csv', 'LD Data for training.csv']
feature 항목 :  Index(['CONTAINER_NO', 'VESSEL', 'MCHN_ID', 'FULL_EMPTY', 'JOB_TYPE', 'POD',
       'BLOCK_BAY', 'JOB_START_DT', 'JOB_END_DT', 'CHE_ID', 'ITV_ID', 'QC_ID',
       'OUTSERVICE', 'QUEUE_POSITION', 'H_BOX', 'OUTVESSEL', 'COUNTRY_NEXTPOD',
       'PORT_NEXTPOD', 'TML_OUT_DT'],
      dtype='object')

,CONTAINER_NO,VESSEL,MCHN_ID,FULL_EMPTY,JOB_TYPE,POD,BLOCK_BAY,JOB_START_DT,JOB_END_DT,CHE_ID,ITV_ID,QC_ID,OUTSERVICE,QUEUE_POSITION,H_BOX,OUTVESSEL,COUNTRY_NEXTPOD,PORT_NEXTPOD,TML_OUT_DT
0,UESU4586161-1,SXNW-001/2018,GC110,F,DS-QUAYSIDE,KRPUS,2B-74,2018-01-29 20:19:45.000,2018-01-29 20:21:17.000,NaN,NaN,NaN,NaN,18D-D,1329.0,MSSO-001/2018,CN,NGB,2.018021e+13
1,UESU4586161-1,SXNW-001/2018,YT529,F,DS-MOVE,KRPUS,2B-74,2018-01-29 20:21:17.000,2018-01-29 20:33:17.000,TC224,YT529,GC110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UESU4586161-1,SXNW-001/2018,TC224,F,DS-YARDSIDE,KRPUS,2B-74,2018-01-29 20:33:17.000,2018-01-29 20:34:49.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UESU4153686-1,SXNW-001/2018,GC109,F,DS-QUAYSIDE,KRPUS,1C-10,2018-01-29 20:16:40.000,2018-01-29 20:18:12.000,NaN,NaN,NaN,NaN,06H-D,1329.0,NaN,NaN,NaN,NaN
4,UESU4153686-1,SXNW-001/2018,YT526,F,DS-MOVE,KRPUS,1C-10,2018-01-29 20:18:12.000,2018-01-29 20:30:32.000,TC231,YT526,GC109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188596,BGBU5060490-3,ALAP-001/2018,YT538,F,DS-MOVE,KRPUS,3F-69,2018-01-31 20:59:20.000,2018-01-31 21:11:32.000,TC266,YT538,GC109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188597,BGBU5060490-3,ALAP-001/2018,TC266,F,DS-YARDSIDE,KRPUS,3F-69,2018-01-31 21:11:32.000,2018-01-31 21:13:04.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188598,AXIU1484082-2,ALAP-001/2018,GC112,F,DS-QUAYSIDE,KRPUS,1B-38,2018-01-31 21:17:52.000,2018-01-31 21:19:24.000,NaN,NaN,NaN,NaN,46H-D,531.0,MGIR-001/2018,US,HOU,2.018020e+13
188599,AXIU1484082-2,ALAP-001/2018,YT511,F,DS-MOVE,KRPUS,1B-38,2018-01-31 21:19:24.000,2018-01-31 21:36:33.000,TC221,YT511,GC112,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188600,AXIU1484082-2,ALAP-001/2018,TC221,F,DS-YARDSIDE,KRPUS,1B-38,2018-01-31 21:36:33.000,2018-01-31 21:38:05.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.isnull().sum()

CONTAINER_NO            0
VESSEL                  0
MCHN_ID             39651
FULL_EMPTY              0
JOB_TYPE                0
POD                     0
BLOCK_BAY           39651
JOB_START_DT            0
JOB_END_DT              0
CHE_ID             138770
ITV_ID             138770
QC_ID              138952
OUTSERVICE         148950
QUEUE_POSITION     138951
H_BOX              138951
OUTVESSEL          183094
COUNTRY_NEXTPOD    183094
PORT_NEXTPOD       183094
TML_OUT_DT         183783
dtype: int64

# 데이터 전처리

In [4]:
# gate perspective에서 연관지어 GI에 대한 정보가 있는 컨테이너들을 추출한다. - Dwell time을 계산하기 위해서
os.chdir("C:\\Users\hyunj\\Dropbox\\종합설계프로젝트\\중요\\데이터")
gate_data = pd.read_csv('GO perspective.csv')

gate_data.drop('Variant', axis = 1, inplace = True)
gate_data.drop('Variant index', axis = 1, inplace = True)

gate_data.rename(columns = {'Case ID':'CONTAINER_NO',
                       'Activity':'JOB_TYPE',
                       'Start Timestamp': 'JOB_START_DT',
                       'Complete Timestamp' : 'JOB_END_DT'},
                        inplace=True)
gate_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39728 entries, 0 to 39727
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CONTAINER_NO  39728 non-null  object
 1   JOB_TYPE      39728 non-null  object
 2   JOB_START_DT  39728 non-null  object
 3   JOB_END_DT    39728 non-null  object
 4   VESSEL        39728 non-null  object
 5   POD           39728 non-null  object
 6   OUTSERVICE    39728 non-null  object
 7   FULL_EMPTY    39728 non-null  object
dtypes: object(8)
memory usage: 2.4+ MB

In [5]:
# gate perspective에서 GI 정보가 있는 Container만을 통합된 LD 데이터에서 가져온다.
unique_container_list_in_integrated_data = list(data['CONTAINER_NO'].unique())
unique_container_list_out_gate = list(gate_data['CONTAINER_NO'].unique())

unique_container_list_in_integrated_data = set(unique_container_list_in_integrated_data)
unique_container_list_out_gate = set(unique_container_list_out_gate)

common_container = unique_container_list_in_integrated_data & unique_container_list_out_gate

print("GO 정보가 있는 총 LD 컨테이너 수 :", len(common_container))

GO 정보가 있는 총 LD 컨테이너 수 : 39651

In [6]:
# 추출
data = data[data['CONTAINER_NO'].isin(common_container)]

In [7]:
data.isnull().sum()
# 가장 중요한 JOB_START_DT와 JOB_END_DT에서 결측치가 확인되지 않아 바로 전처리 수행

CONTAINER_NO            0
VESSEL                  0
MCHN_ID             39651
FULL_EMPTY              0
JOB_TYPE                0
POD                     0
BLOCK_BAY           39651
JOB_START_DT            0
JOB_END_DT              0
CHE_ID             118771
ITV_ID             118771
QC_ID              118953
OUTSERVICE         118953
QUEUE_POSITION     118953
H_BOX              118953
OUTVESSEL          158302
COUNTRY_NEXTPOD    158302
PORT_NEXTPOD       158302
TML_OUT_DT         158302
dtype: int64

In [8]:
#! 데이터 삭제
# DS는 OUTVESSEL, COUNTRY_NEXTPOD, PORT_NEXTPOD, TML_OUT_DT 등에 관한 데이터는 필요 없으니 삭제
# DS는 OUTSERVICE 값이 전부 NULL이 아니기 때문에 포함
data.drop(["OUTVESSEL", "COUNTRY_NEXTPOD", "PORT_NEXTPOD", "TML_OUT_DT"], axis=1, inplace=True)

C:\Users\hyunj\AppData\Local\Temp\ipykernel_9324\1727174072.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(["OUTVESSEL", "COUNTRY_NEXTPOD", "PORT_NEXTPOD", "TML_OUT_DT"], axis=1, inplace=True)

In [9]:
data['JOB_START_DT'] = pd.to_datetime(data['JOB_START_DT'])
data['JOB_END_DT'] = pd.to_datetime(data['JOB_END_DT'])
data.info()

C:\Users\hyunj\AppData\Local\Temp\ipykernel_9324\1956829944.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['JOB_START_DT'] = pd.to_datetime(data['JOB_START_DT'])
C:\Users\hyunj\AppData\Local\Temp\ipykernel_9324\1956829944.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['JOB_END_DT'] = pd.to_datetime(data['JOB_END_DT'])

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158604 entries, 3 to 188579
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   CONTAINER_NO    158604 non-null  object
 1   VESSEL          158604 non-null  object
 2   MCHN_ID         118953 non-null  object
 3   FULL_EMPTY      158604 non-null  object
 4   JOB_TYPE        158604 non-null  object
 5   POD             158604 non-null  object
 6   BLOCK_BAY       118953 non-null  object
 7   JOB_START_DT    158604 non-null  datetime64[ns]
 8   JOB_END_DT      158604 non-null  datetime64[ns]
 9   CHE_ID          39833 non-null   object
 10  ITV_ID          39833 non-null   object
 11  QC_ID           39651 non-null   object
 12  OUTSERVICE      39651 non-null   object
 13  QUEUE_POSITION  39651 non-null   object
 14  H_BOX           39651 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(12)
memory usage: 19.4+ MB

In [10]:
container_list = list(data['CONTAINER_NO'].unique())
print(len(container_list))

39651

In [66]:
# 데이터 프레임을 다시 학습할 수 있도록 데이터를 변환
#! 사용한 Feature들은 파워포인트 참고

# 여기에서 DWELL TIME은 단순한 STORAGE TIME을 의미해서 작업 시간에 대한 변수도 DS-MOVE 밖에 없음
# 빈 데이터 프레임 생성(최종 사용할 데이터)
last_df = pd.DataFrame(columns=["CONTAINER_NO", "LD_VESSEL_ID", "LD_VESSEL_YEAR", 
                                "LD_COUNTRY_POD", "LD_CITY_POD", "Full_Empty", "LD_BLOCK", "LD_BAY", 
                                "LD_CHE_ID", "LD_ITV_ID", "LD_QC_ID", "LD_EXTERNAL_TRUCK",
                                "LD_QUEUE_POSITION_NUMBER", "LD_QUEUE_POSITION_HACK_DACK", "LD_H_BOX",
                                "LD_DAY", "GI_DAY", "Dwell Time"])
i = 0

# Continous Data 변환
for container in tqdm(container_list, desc = "학습할 데이터 생성 중") : 
    temp_df = data[data['CONTAINER_NO'] == container].reset_index(drop=True)
    
    #! Dwell Time(Target) 계산 
    gate_in = temp_df[temp_df['JOB_TYPE'] == 'GI'].loc[:, 'JOB_END_DT'][3]
    start_LD = temp_df[temp_df['JOB_TYPE'] == 'LD-YARDSIDE'].loc[:, 'JOB_START_DT'][0]
    dwell_time = (start_LD - gate_in).days * 24 * 60 * 60 + (start_LD - gate_in).seconds
    
    #! ContainerID
    # 혹시 4개의 작업의 Container 들이 다를 수 있으니 이를 확인
    if (temp_df.loc[0, "CONTAINER_NO"] == temp_df.loc[1, "CONTAINER_NO"] == temp_df.loc[2, "CONTAINER_NO"] == temp_df.loc[3, "CONTAINER_NO"]) :
        container_id = temp_df.loc[3, "CONTAINER_NO"][:4]
    else :
        print(container, "의 경우 컨테이너 ID가 일치하지 않습니다")
        break
    
    #! LD-Vessel ID
    # 혹시 4개의 작업에 Vessel 아이디가 다를 수도 있으니 이를 확인
    if (temp_df.loc[0, "VESSEL"].split("/")[0] == temp_df.loc[1, "VESSEL"].split("/")[0] == temp_df.loc[2, "VESSEL"].split("/")[0]
        == temp_df.loc[3, "VESSEL"].split("/")[0]) :
        ld_vessel_id = temp_df.loc[0, "VESSEL"][:4]
    else :
        print(container, "의 경우 3개의 LD-VESSEL ID가 일치하지 않습니다")
        break
    
    #! LD-Vessel Year
    # 혹시 4개의 작업에 Vessel 아이디가 다를 수도 있으니 이를 확인
    if (temp_df.loc[0, "VESSEL"].split("/")[1] == temp_df.loc[1, "VESSEL"].split("/")[1] == temp_df.loc[2, "VESSEL"].split("/")[1]
        == temp_df.loc[3, "VESSEL"].split("/")[1]) :
        ld_vessel_year = temp_df.loc[0, "VESSEL"].split("/")[1]
    else :
        print(container, "의 경우 3개의 LD-VESSEL 년도가 일치하지 않습니다")
        break
    
    #! LD-POD
    # 점검
    if (temp_df.loc[0, "POD"] == temp_df.loc[1, "POD"] == temp_df.loc[2, "POD"] == temp_df.loc[3, "POD"]) :
        pod_country_ld = temp_df.loc[0, "POD"][:2]
        pod_city_ld = temp_df.loc[0, "POD"][2:]
    else :
        print(container, "의 경우 3개의 LD의 POD가 일치하지 않습니다")
        break
    
    #! FULL / EMPTY
    # 4가지의 경우에 다 같은지 확인
    if (temp_df.loc[0, "FULL_EMPTY"] == temp_df.loc[1, "FULL_EMPTY"] == temp_df.loc[2, "FULL_EMPTY"]
        == temp_df.loc[3, "FULL_EMPTY"] ) :
        full_empty = temp_df.loc[0, "FULL_EMPTY"]
    else :
        print(container, "의 경우 6개의 FULL/EMPTY가 일치하지 않습니다")
        break
    
    #! BLOCK_BAY
    if (temp_df.loc[0, "BLOCK_BAY"] == temp_df.loc[1, "BLOCK_BAY"] == temp_df.loc[2, "BLOCK_BAY"]) :
        # P1 P2 P3 의 값이 있는 것을 확인
        if("-" in temp_df.loc[0, "BLOCK_BAY"]) : 
            temp_block_bay = temp_df.loc[0, "BLOCK_BAY"].split('-')
            ld_block = str(int(temp_block_bay[0][:-1])) + temp_block_bay[0][-1]
            ld_bay = temp_block_bay[1]
        else :
            ld_block = temp_df.loc[0, "BLOCK_BAY"]
            ld_bay = temp_df.loc[0, "BLOCK_BAY"]
        
    #! LD_CHE_ID, LD_ITV_ID, LD_QC_ID, 
    # 이미 이전까지 이 데이터셋을 통합하는데 문제 없다고 판단함
    ld_che_id = temp_df.loc[0, "MCHN_ID"] # = LD_YARDSIDE의 장비
    ld_itv_id = temp_df.loc[1, "MCHN_ID"] # = LD_MOVE의 장비
    ld_qc_id = temp_df.loc[2, "MCHN_ID"] # = LD_QUAYSIDE의 장비
    ld_external_truck_id = temp_df.loc[3, "ITV_ID"]
    
    #! LD_QUEUEPOSITION & DS_QUEUEPOSITION & COUNTRY_NEXTPOD & PORT_NEXTPOD & TML_DT_OUT
    ld_temp = temp_df.loc[2, "QUEUE_POSITION"].split("-")[0]
    ld_queue_position_number = ld_temp[:2]
    ld_queue_position_hack_deck = ld_temp[2]
    ld_h_box = temp_df.loc[2, "H_BOX"]

    #! 요일
    ld_day = temp_df.loc[0, 'JOB_START_DT'].day_name()
    gate_in_day = temp_df.loc[3, "JOB_START_DT"].day_name()

    #! 전처리한 값 집어넣어주기
    row_list = [container_id, ld_vessel_id, ld_vessel_year, pod_country_ld, pod_city_ld, full_empty, 
                ld_block, ld_bay, ld_che_id, ld_itv_id, ld_qc_id, ld_external_truck_id,
                ld_queue_position_number, ld_queue_position_hack_deck, ld_h_box, 
                ld_day, gate_in_day,
                dwell_time]
    last_df.loc[i, :] = row_list
    i += 1

학습할 데이터 생성 중: 100%|██████████| 36941/36941 [14:04<00:00, 43.73it/s]

In [67]:
last_df.info()
os.chdir("C:\\Users\hyunj\\Dropbox\\종합설계프로젝트\\중요\\데이터\\통합")
last_df.to_csv('LD Data for training.csv', index=False, encoding='CP949')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36941 entries, 0 to 36940
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CONTAINER_NO                 36941 non-null  object
 1   LD_VESSEL_ID                 36941 non-null  object
 2   LD_VESSEL_YEAR               36941 non-null  object
 3   LD_COUNTRY_POD               36941 non-null  object
 4   LD_CITY_POD                  36941 non-null  object
 5   Full_Empty                   36941 non-null  object
 6   LD_BLOCK                     36941 non-null  object
 7   LD_BAY                       36941 non-null  object
 8   LD_CHE_ID                    36941 non-null  object
 9   LD_ITV_ID                    36932 non-null  object
 10  LD_QC_ID                     36941 non-null  object
 11  LD_EXTERNAL_TRUCK            36912 non-null  object
 12  LD_QUEUE_POSITION_NUMBER     36941 non-null  object
 13  LD_QUEUE_POSITION_HACK_DACK  36941 non-null  object
 14  LD_H_BOX                     36941 non-null  object
 15  LD_DAY                       36941 non-null  object
 16  GI_DAY                       36941 non-null  object
 17  Dwell Time                   36941 non-null  object
dtypes: object(18)
memory usage: 6.4+ MB